version: "2"

linters:
  enable:
    - gocritic
    - gosec
    - errorlint
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G204
        - G301
        - G304
        - G306
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
