package generate

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

var (
	// thorDefaultCleanRe strips bare Default: value from descriptions.
	thorDefaultCleanRe = regexp.MustCompile(`\s*\bDefault:\s+\S+`)

	// possibleValuesCleanRe strips Possible values: ... from descriptions.
	possibleValuesCleanRe = regexp.MustCompile(`(?i)\s*Possible values?:\s*.*`)
)

// scaffoldWizard is the minimal YAML-serializable wizard for scaffold output.
type scaffoldWizard struct {
	Name        string           `yaml:"name"`
	Description string           `yaml:"description"`
	Command     string           `yaml:"command"`
	Options     []scaffoldOption `yaml:"options"`
}

// scaffoldOption is a minimal YAML-serializable wizard option.
type scaffoldOption struct {
	Name        string   `yaml:"name"`
	Type        string   `yaml:"type"`
	Label       string   `yaml:"label"`
	Description string   `yaml:"description,omitempty"`
	Flag        string   `yaml:"flag,omitempty"`
	Default     any      `yaml:"default,omitempty"`
	Choices     []string `yaml:"choices,omitempty,flow"`
}

// EmitConfig holds parameters for YAML generation.
type EmitConfig struct {
	Name    string // wizard name.
	Command string // base command, e.g. "docker run".
}

// Emit converts parsed flags into a wizard YAML scaffold string.
func Emit(cfg EmitConfig, flags []Flag) string {
	w := scaffoldWizard{
		Name:        cfg.Name,
		Description: "",
		Command:     cfg.Command,
		Options:     make([]scaffoldOption, 0, len(flags)),
	}

	seen := make(map[string]int, len(flags))
	for _, f := range flags {
		opt := flagToOption(f)
		if n, ok := seen[opt.Name]; ok {
			seen[opt.Name] = n + 1
			opt.Name = opt.Name + "_" + strconv.Itoa(n+1)
		} else {
			seen[opt.Name] = 1
		}
		w.Options = append(w.Options, opt)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by: oz generate %s\n", cfg.Command)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	_ = enc.Encode(w)
	_ = enc.Close()

	return buf.String()
}

// flagToOption converts a parsed Flag to a scaffold option.
func flagToOption(f Flag) scaffoldOption {
	opt := scaffoldOption{
		Name:        deriveName(f),
		Label:       deriveLabel(f),
		Description: cleanDescription(f.Description),
		Flag:        preferredFlag(f),
	}

	switch {
	case len(f.EnumValues) > 0:
		opt.Type = "select"
		opt.Choices = f.EnumValues
		if f.Default != "" {
			opt.Default = f.Default
		}
	case isBoolFlag(f):
		opt.Type = "confirm"
		opt.Default = f.Default == boolTrue
	default:
		opt.Type = "input"
		if f.Default != "" && f.Default != "\"\"" && f.Default != "''" {
			opt.Default = f.Default
		}
	}

	return opt
}

const boolTrue = "true"

// isBoolFlag returns true if the flag looks like a boolean toggle.
func isBoolFlag(f Flag) bool {
	if f.Placeholder != "" {
		return false
	}
	switch f.Default {
	case "", boolTrue, "false":
		return true
	}
	return false
}

// deriveName creates an option name from the flag.
// --dry-run → dry_run, --output → output, -v → v.
func deriveName(f Flag) string {
	name := f.Long
	if name == "" {
		name = f.Short
	}
	name = strings.TrimLeft(name, "-")
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, ".", "_")
	return name
}

// deriveLabel creates a human-readable label from the flag name.
// --dry-run → "Dry run", -v → "V".
func deriveLabel(f Flag) string {
	name := f.Long
	if name == "" {
		name = f.Short
	}
	name = strings.TrimLeft(name, "-")
	name = strings.ReplaceAll(name, "-", " ")
	name = strings.ReplaceAll(name, "_", " ")
	if name == "" {
		return ""
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

// preferredFlag returns the flag to use in the wizard config.
// Prefers long form; falls back to short.
func preferredFlag(f Flag) string {
	if f.Long != "" {
		return f.Long
	}
	return f.Short
}

// cleanDescription trims and removes default/enum annotations.
func cleanDescription(s string) string {
	s = strings.TrimSpace(s)
	// Remove (default ...) or [default ...].
	s = defaultRe.ReplaceAllString(s, "")
	// Remove bare Default: value (Thor convention).
	s = thorDefaultCleanRe.ReplaceAllString(s, "")
	// Remove Possible values: ... (Thor convention).
	s = possibleValuesCleanRe.ReplaceAllString(s, "")
	// Remove orphaned leading ", " from stripped negation variants.
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, ", ")
	s = strings.TrimSpace(s)
	// Ensure sentence ending.
	if s != "" && !strings.HasSuffix(s, ".") && !strings.HasSuffix(s, "?") && !strings.HasSuffix(s, "!") {
		s += "."
	}
	return s
}
