package generate

import (
	"strings"
	"testing"

	"github.com/svyatov/oz/internal/config"
)

func TestEmit_BasicFlags(t *testing.T) {
	flags := []Flag{
		{Long: "--verbose", Description: "enable verbose output"},
		{Long: "--output", Short: "-o", Placeholder: "FILE", Description: "output file path"},
		{
			Long: "--format", Placeholder: "{json,csv,txt}", Description: "output format",
			Default: "json", EnumValues: []string{"json", "csv", "txt"},
		},
		{Long: "--count", Placeholder: "NUM", Description: "number of iterations", Default: "10"},
	}

	yaml := Emit(EmitConfig{Name: "test-tool", Command: "test-tool"}, flags)

	// Check header comment.
	if !strings.HasPrefix(yaml, "# Generated by: oz generate test-tool\n") {
		t.Errorf("missing header comment, got:\n%s", yaml[:80])
	}

	// Check name and command.
	if !strings.Contains(yaml, "name: test-tool") {
		t.Error("missing name field")
	}
	if !strings.Contains(yaml, "command: test-tool") {
		t.Error("missing command field")
	}

	// Check verbose is a confirm type.
	if !strings.Contains(yaml, "type: confirm") {
		t.Error("--verbose should be confirm type")
	}

	// Check format has choices.
	if !strings.Contains(yaml, "choices: [json, csv, txt]") {
		t.Errorf("--format should have choices, got:\n%s", yaml)
	}
}

func TestEmit_RoundTrip(t *testing.T) {
	// Parse real help text, emit YAML, then parse with config.ParseWizard.
	flags := Parse(cobraHelp)
	yamlStr := Emit(EmitConfig{Name: "go-build", Command: "go build"}, flags)

	w, err := config.ParseWizard([]byte(yamlStr))
	if err != nil {
		t.Fatalf("ParseWizard failed: %v\nyaml:\n%s", err, yamlStr)
	}

	if w.Name != "go-build" {
		t.Errorf("Name = %q, want %q", w.Name, "go-build")
	}
	if w.Command != "go build" {
		t.Errorf("Command = %q, want %q", w.Command, "go build")
	}
	if len(w.Options) != 5 {
		t.Errorf("got %d options, want 5", len(w.Options))
	}

	// Verify each option has the required fields.
	for _, o := range w.Options {
		if o.Name == "" {
			t.Error("option has empty name")
		}
		if o.Label == "" {
			t.Errorf("option %q has empty label", o.Name)
		}
		if !o.Type.IsValid() {
			t.Errorf("option %q has invalid type %q", o.Name, o.Type)
		}
	}
}

func TestEmit_RoundTripValidates(t *testing.T) {
	// Parse Docker help, emit, then validate.
	flags := Parse(dockerRunHelp)
	yamlStr := Emit(EmitConfig{Name: "docker-run", Command: "docker run"}, flags)

	w, err := config.ParseWizard([]byte(yamlStr))
	if err != nil {
		t.Fatalf("ParseWizard failed: %v\nyaml:\n%s", err, yamlStr)
	}

	errs := config.Validate(w)
	if len(errs) > 0 {
		t.Errorf("Validate returned errors:\n%s\nyaml:\n%s",
			config.FormatErrors(errs), yamlStr)
	}
}

func TestEmit_ArgparseEnum(t *testing.T) {
	flags := Parse(argparseHelp)
	yamlStr := Emit(EmitConfig{Name: "my-tool", Command: "mytool"}, flags)

	w, err := config.ParseWizard([]byte(yamlStr))
	if err != nil {
		t.Fatalf("ParseWizard failed: %v", err)
	}

	// Find the format option — should be select with choices.
	var formatOpt *config.Option
	for i := range w.Options {
		if w.Options[i].Name == "format" {
			formatOpt = &w.Options[i]
			break
		}
	}
	if formatOpt == nil {
		t.Fatal("format option not found")
	}
	if formatOpt.Type != config.OptionSelect {
		t.Errorf("format type = %q, want %q", formatOpt.Type, config.OptionSelect)
	}
	if len(formatOpt.Choices) != 3 {
		t.Errorf("format choices count = %d, want 3", len(formatOpt.Choices))
	}
}

func TestEmit_ConfirmDefault(t *testing.T) {
	flags := []Flag{
		{Long: "--detach", Description: "run in background", Default: "false"},
		{Long: "--force", Description: "force operation", Default: "true"},
	}

	yamlStr := Emit(EmitConfig{Name: "test", Command: "test"}, flags)

	w, err := config.ParseWizard([]byte(yamlStr))
	if err != nil {
		t.Fatalf("ParseWizard failed: %v\nyaml:\n%s", err, yamlStr)
	}

	for _, o := range w.Options {
		if o.Type != config.OptionConfirm {
			t.Errorf("option %q type = %q, want confirm", o.Name, o.Type)
		}
	}

	// --force should have default: true.
	for _, o := range w.Options {
		if o.Name == "force" {
			if o.Default == nil || !o.Default.Bool() {
				t.Error("--force should have default: true")
			}
		}
	}
}

func TestEmit_EmptyFlags(t *testing.T) {
	yamlStr := Emit(EmitConfig{Name: "empty", Command: "empty"}, nil)

	w, err := config.ParseWizard([]byte(yamlStr))
	if err != nil {
		t.Fatalf("ParseWizard failed: %v", err)
	}
	if len(w.Options) != 0 {
		t.Errorf("got %d options, want 0", len(w.Options))
	}
}
